%YAML:1.0
---
model_type: PINHOLE
camera_name: left
image_width: 640
image_height: 360
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 554.3827128226441
   fy: 554.3827128226441
   cx: 320.5
   cy: 180.5
