%YAML:1.0
---
# Common parameters
imu: 1
num_of_cam: 2

imu_topic: "/imu_plugin/out"
image0_topic: "/stereocamera/left/image_raw"
image1_topic: "/stereocamera/right/image_raw"
output_path: "/home/roy/output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 360

# GPU acceleration
use_gpu: 0
use_gpu_acc_flow: 0
use_gpu_ceres: 0

# Extrinsic parameter between IMU and Camera
estimate_extrinsic: 1

body_T_cam0: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [
        -5.7586305857e-03, -4.0463318787e-03, 9.9997523237e-01, 2.032926e-02,
        -9.9998287214e-01, -1.0224590553e-03, -5.7628118925e-03, 7.93252e-03,
        1.04575198e-03, -9.999912908e-01, -4.040374609e-03, 2.8559824645e-03,
        0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [
        -1.0021770212e-03, 3.6313480322e-04, 9.9999943188e-01, 1.5285779566e-02,
        -9.9999216342e-01, -3.8303422615e-03, -1.0007788055e-03, -5.2435791e-02,
        3.8299766679e-03, -9.9999259827e-01, 3.6697063849e-04, 8.6931302450e-03,
        0.0, 0.0, 0.0, 1.0]
# Multiple thread support
multiple_thread: 1

# Feature tracker parameters
max_cnt: 150          # Max feature number in feature tracking
min_dist: 30          # Min distance between two features
freq: 10              # Frequency (Hz) of tracking result publication
F_threshold: 1.0      # RANSAC threshold (pixel)
show_track: 1         # Publish tracking image as topic
flow_back: 1

# Optimization parameters
max_solver_time: 0.04  # Max solver iteration time (ms)
max_num_iterations: 8  # Max solver iterations
keyframe_parallax: 10.0  # Keyframe selection threshold (pixel)

# IMU parameters
acc_n: 0.1      # Accelerometer measurement noise std deviation
gyr_n: 0.01     # Gyroscope measurement noise std deviation
acc_w: 0.001    # Accelerometer bias random walk noise std deviation
gyr_w: 0.0001   # Gyroscope bias random walk noise std deviation
g_norm: 9.805   # Gravity magnitude

# Unsynchronization parameters
estimate_td: 1  # Online estimation of time offset between camera and IMU
td: 0

# Loop closure parameters
load_previous_pose_graph: 1  # Load and reuse previous pose graph
detect_loop: 1               # Enable loop detection
pose_graph_save_path: "/home/roy/output/pose_graph/"  # Save/load path
save_image: 1  # Save image in pose graph for visualization
