%YAML 1.0

#common parameters
imu: 1         
num_of_cam: 1 

imu_topic: "dji_sdk_1/dji_sdk/imu"
image0_topic: "hcfox_1/image"
output_path: "~/output/"

image_width: 752
image_height: 480
cam0_calib: "left_mei.yaml"

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam

# extrinsicRotation: !!opencv-matrix
body_T_cam0: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 5.6075828145143336e-02, -7.2159314759991836e-02,
       9.9581551242748023e-01, -9.9782044945128112e-01,
       -3.8796951305458682e-02, 5.3377403704616570e-02,
       3.4782929069876567e-02, -9.9663826429791991e-01,
       -7.4177611059871973e-02 ]
body_T_cam0: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 7.7766363536769759e-02, 1.7519580132927693e-02,
       -1.6725607824124328e-02 ]
   

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 120
min_dist: 30
freq: 10
F_threshold: 3.0
show_track: 0
equalize: 0 
fisheye: 1
flow_back: 1  
#optimization parameters
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0

#imu parameters
acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.04         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805     # gravity magnitude

#unsynchronization parameters
estimate_td: 1
td: 0.0

rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0 

#loop closure parameters
load_previous_pose_graph: 0
pose_graph_save_path: "~/output/pose_graph/"
save_image: 0
visualize_imu_forward: 0
visualize_camera_size: 0.4

swarm_agent: 1
